from .feature_set import Features_Set

class Features_PSSM(Features_Set):
    __features_order__ = ["Substitution_score_mean_A","Substitution_score_mean_R","Substitution_score_mean_N","Substitution_score_mean_D","Substitution_score_mean_C","Substitution_score_mean_Q",
                        "Substitution_score_mean_E","Substitution_score_mean_G","Substitution_score_mean_H","Substitution_score_mean_I","Substitution_score_mean_L","Substitution_score_mean_K",
                        "Substitution_score_mean_M","Substitution_score_mean_F","Substitution_score_mean_P","Substitution_score_mean_S","Substitution_score_mean_T","Substitution_score_mean_W",
                        "Substitution_score_mean_Y","Substitution_score_mean_V","Weighted_observed_percentages_mean_A","Weighted_observed_percentages_mean_R","Weighted_observed_percentages_mean_N",
                        "Weighted_observed_percentages_mean_D","Weighted_observed_percentages_mean_C","Weighted_observed_percentages_mean_Q","Weighted_observed_percentages_mean_E",
                        "Weighted_observed_percentages_mean_G","Weighted_observed_percentages_mean_H","Weighted_observed_percentages_mean_I","Weighted_observed_percentages_mean_L",
                        "Weighted_observed_percentages_mean_K","Weighted_observed_percentages_mean_M","Weighted_observed_percentages_mean_F","Weighted_observed_percentages_mean_P",
                        "Weighted_observed_percentages_mean_S","Weighted_observed_percentages_mean_T","Weighted_observed_percentages_mean_W","Weighted_observed_percentages_mean_Y",
                        "Weighted_observed_percentages_mean_V","Mean_information_per_position_mean","Rel_wt_gapless_pseudocount_mean","Substitution_score_mean_A","Substitution_score_mean_R",
                        "Substitution_score_mean_N","Substitution_score_mean_D","Substitution_score_mean_C","Substitution_score_mean_Q","Substitution_score_mean_E","Substitution_score_mean_G",
                        "Substitution_score_mean_H","Substitution_score_mean_I","Substitution_score_mean_L","Substitution_score_mean_K","Substitution_score_mean_M","Substitution_score_mean_F",
                        "Substitution_score_mean_P","Substitution_score_mean_S","Substitution_score_mean_T","Substitution_score_mean_W","Substitution_score_mean_Y","Substitution_score_mean_V",
                        "Weighted_observed_percentages_mean_A","Weighted_observed_percentages_mean_R","Weighted_observed_percentages_mean_N","Weighted_observed_percentages_mean_D","Weighted_observed_percentages_mean_C",
                        "Weighted_observed_percentages_mean_Q","Weighted_observed_percentages_mean_E","Weighted_observed_percentages_mean_G","Weighted_observed_percentages_mean_H","Weighted_observed_percentages_mean_I",
                        "Weighted_observed_percentages_mean_L","Weighted_observed_percentages_mean_K","Weighted_observed_percentages_mean_M","Weighted_observed_percentages_mean_F","Weighted_observed_percentages_mean_P",
                        "Weighted_observed_percentages_mean_S","Weighted_observed_percentages_mean_T","Weighted_observed_percentages_mean_W","Weighted_observed_percentages_mean_Y","Weighted_observed_percentages_mean_V",
                        "Mean_information_per_position_mean","Rel_wt_gapless_pseudocount_mean","Substitution_score_mean_A","Substitution_score_mean_R","Substitution_score_mean_N","Substitution_score_mean_D",
                        "Substitution_score_mean_C","Substitution_score_mean_Q","Substitution_score_mean_E","Substitution_score_mean_G","Substitution_score_mean_H","Substitution_score_mean_I","Substitution_score_mean_L",
                        "Substitution_score_mean_K","Substitution_score_mean_M","Substitution_score_mean_F","Substitution_score_mean_P","Substitution_score_mean_S","Substitution_score_mean_T","Substitution_score_mean_W",
                        "Substitution_score_mean_Y","Substitution_score_mean_V","Weighted_observed_percentages_mean_A","Weighted_observed_percentages_mean_R","Weighted_observed_percentages_mean_N",
                        "Weighted_observed_percentages_mean_D","Weighted_observed_percentages_mean_C","Weighted_observed_percentages_mean_Q","Weighted_observed_percentages_mean_E","Weighted_observed_percentages_mean_G",
                        "Weighted_observed_percentages_mean_H","Weighted_observed_percentages_mean_I","Weighted_observed_percentages_mean_L","Weighted_observed_percentages_mean_K","Weighted_observed_percentages_mean_M",
                        "Weighted_observed_percentages_mean_F","Weighted_observed_percentages_mean_P","Weighted_observed_percentages_mean_S","Weighted_observed_percentages_mean_T","Weighted_observed_percentages_mean_W",
                        "Weighted_observed_percentages_mean_Y","Weighted_observed_percentages_mean_V","Mean_information_per_position_mean","Rel_wt_gapless_pseudocount_mean","Substitution_score_mean_A","Substitution_score_mean_R",
                        "Substitution_score_mean_N","Substitution_score_mean_D","Substitution_score_mean_C","Substitution_score_mean_Q","Substitution_score_mean_E","Substitution_score_mean_G","Substitution_score_mean_H",
                        "Substitution_score_mean_I","Substitution_score_mean_L","Substitution_score_mean_K","Substitution_score_mean_M","Substitution_score_mean_F","Substitution_score_mean_P","Substitution_score_mean_S",
                        "Substitution_score_mean_T","Substitution_score_mean_W","Substitution_score_mean_Y","Substitution_score_mean_V","Weighted_observed_percentages_mean_A","Weighted_observed_percentages_mean_R",
                        "Weighted_observed_percentages_mean_N","Weighted_observed_percentages_mean_D","Weighted_observed_percentages_mean_C","Weighted_observed_percentages_mean_Q","Weighted_observed_percentages_mean_E",
                        "Weighted_observed_percentages_mean_G","Weighted_observed_percentages_mean_H","Weighted_observed_percentages_mean_I","Weighted_observed_percentages_mean_L","Weighted_observed_percentages_mean_K",
                        "Weighted_observed_percentages_mean_M","Weighted_observed_percentages_mean_F","Weighted_observed_percentages_mean_P","Weighted_observed_percentages_mean_S","Weighted_observed_percentages_mean_T",
                        "Weighted_observed_percentages_mean_W","Weighted_observed_percentages_mean_Y","Weighted_observed_percentages_mean_V","Mean_information_per_position_mean","Rel_wt_gapless_pseudocount_mean","PSSM_exist"]