from .feature_set import Features_Set

class Features_Function(Features_Set):
    __features_order__ = "Catalytic_site_wild", "Catalytic_site_mutant", "Catalytic_site_loss", "Catalytic_site_gain", "Calmodulin_binding_wild", "Calmodulin_binding_mutant",
    "Calmodulin_binding_loss", "Calmodulin_binding_gain", "DNA_binding_wild", "DNA_binding_mutant", "DNA_binding_loss", "DNA_binding_gain", "RNA_binding_wild",
    "RNA_binding_mutant", "RNA_binding_loss", "RNA_binding_gain", "PPI_residue_wild", "PPI_residue_mutant", "PPI_residue_loss", "PPI_residue_gain",
    "PPI_hotspot_wild", "PPI_hotspot_mutant", "PPI_hotspot_loss", "PPI_hotspot_gain", "MoRF_wild", "MoRF_mutant", "MoRF_loss", "MoRF_gain", "Allosteric_site_wild",
    "Allosteric_site_mutant", "Allosteric_site_loss", "Allosteric_site_gain", "Cadmium_binding_wild", "Cadmium_binding_mutant", "Cadmium_binding_loss",
    "Cadmium_binding_gain", "Calcium_binding_wild", "Calcium_binding_mutant", "Calcium_binding_loss", "Calcium_binding_gain", "Cobalt_binding_wild", "Cobalt_binding_mutant",
    "Cobalt_binding_loss", "Cobalt_binding_gain", "Copper_binding_wild", "Copper_binding_mutant", "Copper_binding_loss", "Copper_binding_gain", "Iron_binding_wild", 
    "Iron_binding_mutant", "Iron_binding_loss", "Iron_binding_gain", "Magnesium_binding_wild", "Magnesium_binding_mutant", "Magnesium_binding_loss", "Magnesium_binding_gain",
    "Manganese_binding_wild", "Manganese_binding_mutant", "Manganese_binding_loss", "Manganese_binding_gain", "Nickel_binding_wild", "Nickel_binding_mutant", "Nickel_binding_loss",
    "Nickel_binding_gain", "Potassium_binding_wild", "Potassium_binding_mutant", "Potassium_binding_loss", "Potassium_binding_gain", "Sodium_binding_wild", "Sodium_binding_mutant",
    "Sodium_binding_loss", "Sodium_binding_gain", "Zinc_binding_wild", "Zinc_binding_mutant", "Zinc_binding_loss", "Zinc_binding_gain", "Acetylation_wild", "Acetylation_mutant",
    "Acetylation_loss", "Acetylation_gain", "ADP-ribosylation_wild", "ADP-ribosylation_mutant", "ADP-ribosylation_loss", "ADP-ribosylation_gain", "Amidation_wild", "Amidation_mutant",
    "Amidation_loss", "Amidation_gain", "C-linked_glycosylation_wild", "C-linked_glycosylation_mutant", "C-linked_glycosylation_loss", "C-linked_glycosylation_gain", "Carboxylation_wild",
    "Carboxylation_mutant", "Carboxylation_loss", "Carboxylation_gain", "Disulfide_linkage_wild", "Disulfide_linkage_mutant", "Disulfide_linkage_loss", "Disulfide_linkage_gain",
    "Farnesylation_wild", "Farnesylation_mutant", "Farnesylation_loss", "Farnesylation_gain", "Geranylgeranylation_wild", "Geranylgeranylation_mutant", "Geranylgeranylation_loss",
    "Geranylgeranylation_gain", "GPI_anchor_amidation_wild", "GPI_anchor_amidation_mutant", "GPI_anchor_amidation_loss", "GPI_anchor_amidation_gain", "Hydroxylation_wild", "Hydroxylation_mutant",
    "Hydroxylation_loss", "Hydroxylation_gain", "Methylation_wild", "Methylation_mutant", "Methylation_loss", "Methylation_gain", "Myristoylation_wild", "Myristoylation_mutant",
    "Myristoylation_loss", "Myristoylation_gain", "N-linked_glycosylation_wild", "N-linked_glycosylation_mutant", "N-linked_glycosylation_loss", "N-linked_glycosylation_gain",
    "N-terminal_acetylation_wild", "N-terminal_acetylation_mutant", "N-terminal_acetylation_loss", "N-terminal_acetylation_gain", "O-linked_glycosylation_wild", "O-linked_glycosylation_mutant",
    "O-linked_glycosylation_loss", "O-linked_glycosylation_gain", "Palmitoylation_wild", "Palmitoylation_mutant", "Palmitoylation_loss", "Palmitoylation_gain", "Phosphorylation_wild",
    "Phosphorylation_mutant", "Phosphorylation_loss", "Phosphorylation_gain", "Proteolytic_cleavage_wild", "Proteolytic_cleavage_mutant", "Proteolytic_cleavage_loss",
    "Proteolytic_cleavage_gain", "Pyrrolidone_carboxylic_acid_wild", "Pyrrolidone_carboxylic_acid_mutant", "Pyrrolidone_carboxylic_acid_loss", "Pyrrolidone_carboxylic_acid_gain",
    "Sulfation_wild", "Sulfation_mutant", "Sulfation_loss", "Sulfation_gain", "SUMOylation_wild", "SUMOylation_mutant", "SUMOylation_loss", "SUMOylation_gain", "Ubiquitylation_wild",
    "Ubiquitylation_mutant", "Ubiquitylation_loss", "Ubiquitylation_gain", "Motifs_wild", "Motifs_mutant", "Motifs_loss", "Motifs_gain", "Catalytic_site_exist", "Calmodulin_binding_exist",
    "DNA_binding_exist", "RNA_binding_exist", "PPI_residue_exist", "PPI_hotspot_exist", "MoRF_exist", "Allosteric_site_exist", "Cadmium_binding_exist", "Calcium_binding_exist",
    "Cobalt_binding_exist", "Copper_binding_exist", "Iron_binding_exist", "Magnesium_binding_exist", "Manganese_binding_exist", "Nickel_binding_exist", "Potassium_binding_exist",
    "Sodium_binding_exist", "Zinc_binding_exist", "Acetylation_exist", "ADP-ribosylation_exist", "Amidation_exist", "C-linked_glycosylation_exist", "Carboxylation_exist",
    "Disulfide_linkage_exist", "Farnesylation_exist", "Geranylgeranylation_exist", "GPI_anchor_amidation_exist", "Hydroxylation_exist", "Methylation_exist", "Myristoylation_exist",
    "N-linked_glycosylation_exist", "N-terminal_acetylation_exist", "O-linked_glycosylation_exist", "Palmitoylation_exist", "Phosphorylation_exist", "Proteolytic_cleavage_exist",
    "Pyrrolidone_carboxylic_acid_exist", "Sulfation_exist", "SUMOylation_exist", "Ubiquitylation_exist", "Motifs_exist"