from .feature_set import Features_Set

class Features_Sequence(Features_Set):
    __features_order__ = ["AA_frequency_A_3", "AA_frequency_C_3", "AA_frequency_D_3", "AA_frequency_E_3", "AA_frequency_F_3", "AA_frequency_G_3", "AA_frequency_H_3", "AA_frequency_I_3", "AA_frequency_K_3",
                        "AA_frequency_L_3", "AA_frequency_M_3", "AA_frequency_N_3", "AA_frequency_P_3", "AA_frequency_Q_3", "AA_frequency_R_3", "AA_frequency_S_3", "AA_frequency_T_3", "AA_frequency_V_3",
                        "AA_frequency_W_3", "AA_frequency_Y_3", "Entropy_3", "Beta_entropy_1_25_3", "Beta_entropy_1_50_3", "Beta_entropy_1_75_3", "Net_charge_3", "Total_charge_3", "Aromatics_3",
                        "Charge_hydrophobicity_3", "AA_frequency_A_7", "AA_frequency_C_7", "AA_frequency_D_7", "AA_frequency_E_7", "AA_frequency_F_7", "AA_frequency_G_7", "AA_frequency_H_7",
                        "AA_frequency_I_7", "AA_frequency_K_7", "AA_frequency_L_7", "AA_frequency_M_7", "AA_frequency_N_7", "AA_frequency_P_7", "AA_frequency_Q_7", "AA_frequency_R_7",
                        "AA_frequency_S_7", "AA_frequency_T_7", "AA_frequency_V_7", "AA_frequency_W_7", "AA_frequency_Y_7", "Entropy_7", "Beta_entropy_1_25_7", "Beta_entropy_1_50_7",
                        "Beta_entropy_1_75_7", "Net_charge_7", "Total_charge_7", "Aromatics_7", "Charge_hydrophobicity_7", "AA_frequency_A_11", "AA_frequency_C_11", "AA_frequency_D_11",
                        "AA_frequency_E_11", "AA_frequency_F_11", "AA_frequency_G_11", "AA_frequency_H_11", "AA_frequency_I_11", "AA_frequency_K_11", "AA_frequency_L_11", "AA_frequency_M_11",
                        "AA_frequency_N_11", "AA_frequency_P_11", "AA_frequency_Q_11", "AA_frequency_R_11", "AA_frequency_S_11", "AA_frequency_T_11", "AA_frequency_V_11", "AA_frequency_W_11",
                        "AA_frequency_Y_11", "Entropy_11", "Beta_entropy_1_25_11", "Beta_entropy_1_50_11", "Beta_entropy_1_75_11", "Net_charge_11", "Total_charge_11", "Aromatics_11",
                        "Charge_hydrophobicity_11", "AA_frequency_A_21", "AA_frequency_C_21", "AA_frequency_D_21", "AA_frequency_E_21", "AA_frequency_F_21", "AA_frequency_G_21", "AA_frequency_H_21",
                        "AA_frequency_I_21", "AA_frequency_K_21", "AA_frequency_L_21", "AA_frequency_M_21", "AA_frequency_N_21", "AA_frequency_P_21", "AA_frequency_Q_21", "AA_frequency_R_21",
                        "AA_frequency_S_21", "AA_frequency_T_21", "AA_frequency_V_21", "AA_frequency_W_21", "AA_frequency_Y_21", "Entropy_21", "Beta_entropy_1_25_21", "Beta_entropy_1_50_21",
                        "Beta_entropy_1_75_21", "Net_charge_21", "Total_charge_21", "Aromatics_21", "Charge_hydrophobicity_21", "Hydrophobicity_mean_1", "Hydrophobicity_std_1", "Hydrophobicity_max_1",
                        "Hydrophobic_moments_100_mean_1", "Hydrophobic_moments_100_std_1", "Hydrophobic_moments_100_max_1", "Hydrophobic_moments_160_mean_1", "Hydrophobic_moments_160_std_1",
                        "Hydrophobic_moments_160_max_1", "Hydrophobic_moments_120_mean_1", "Hydrophobic_moments_120_std_1", "Hydrophobic_moments_120_max_1", "Vihinen_flexibility_mean_1",
                        "Vihinen_flexibility_std_1", "Vihinen_flexibility_max_1", "Amino_acid_volume_mean_1", "Amino_acid_volume_std_1", "Amino_acid_volume_max_1", "Hydrophobicity_mean_7",
                        "Hydrophobicity_std_7", "Hydrophobicity_max_7", "Hydrophobic_moments_100_mean_7", "Hydrophobic_moments_100_std_7", "Hydrophobic_moments_100_max_7",
                        "Hydrophobic_moments_160_mean_7", "Hydrophobic_moments_160_std_7", "Hydrophobic_moments_160_max_7", "Hydrophobic_moments_120_mean_7", "Hydrophobic_moments_120_std_7",
                        "Hydrophobic_moments_120_max_7", "Vihinen_flexibility_mean_7", "Vihinen_flexibility_std_7", "Vihinen_flexibility_max_7", "Amino_acid_volume_mean_7", "Amino_acid_volume_std_7",
                        "Amino_acid_volume_max_7", "Hydrophobicity_mean_11", "Hydrophobicity_std_11", "Hydrophobicity_max_11", "Hydrophobic_moments_100_mean_11", "Hydrophobic_moments_100_std_11",
                        "Hydrophobic_moments_100_max_11", "Hydrophobic_moments_160_mean_11", "Hydrophobic_moments_160_std_11", "Hydrophobic_moments_160_max_11", "Hydrophobic_moments_120_mean_11",
                        "Hydrophobic_moments_120_std_11", "Hydrophobic_moments_120_max_11", "Vihinen_flexibility_mean_11", "Vihinen_flexibility_std_11", "Vihinen_flexibility_max_11", "Amino_acid_volume_mean_11",
                        "Amino_acid_volume_std_11", "Amino_acid_volume_max_11", "Hydrophobicity_mean_21", "Hydrophobicity_std_21", "Hydrophobicity_max_21", "Hydrophobic_moments_100_mean_21",
                        "Hydrophobic_moments_100_std_21", "Hydrophobic_moments_100_max_21", "Hydrophobic_moments_160_mean_21", "Hydrophobic_moments_160_std_21", "Hydrophobic_moments_160_max_21",
                        "Hydrophobic_moments_120_mean_21", "Hydrophobic_moments_120_std_21", "Hydrophobic_moments_120_max_21", "Vihinen_flexibility_mean_21", "Vihinen_flexibility_std_21",
                        "Vihinen_flexibility_max_21", "Amino_acid_volume_mean_21", "Amino_acid_volume_std_21", "Amino_acid_volume_max_21"]