from .feature_set import Features_Set

class Features_PSSM(Features_Set):
    __features_order__ = ["Substitution_score_mean_A_1", "Substitution_score_mean_R_1", "Substitution_score_mean_N_1",
                          "Substitution_score_mean_D_1", "Substitution_score_mean_C_1", "Substitution_score_mean_Q_1",
                          "Substitution_score_mean_E_1", "Substitution_score_mean_G_1", "Substitution_score_mean_H_1",
                          "Substitution_score_mean_I_1", "Substitution_score_mean_L_1", "Substitution_score_mean_K_1",
                          "Substitution_score_mean_M_1", "Substitution_score_mean_F_1", "Substitution_score_mean_P_1",
                          "Substitution_score_mean_S_1", "Substitution_score_mean_T_1", "Substitution_score_mean_W_1",
                          "Substitution_score_mean_Y_1", "Substitution_score_mean_V_1", "Weighted_observed_percentages_mean_A_1",
                          "Weighted_observed_percentages_mean_R_1", "Weighted_observed_percentages_mean_N_1",
                          "Weighted_observed_percentages_mean_D_1", "Weighted_observed_percentages_mean_C_1",
                          "Weighted_observed_percentages_mean_Q_1", "Weighted_observed_percentages_mean_E_1",
                          "Weighted_observed_percentages_mean_G_1", "Weighted_observed_percentages_mean_H_1",
                          "Weighted_observed_percentages_mean_I_1", "Weighted_observed_percentages_mean_L_1",
                          "Weighted_observed_percentages_mean_K_1", "Weighted_observed_percentages_mean_M_1",
                          "Weighted_observed_percentages_mean_F_1", "Weighted_observed_percentages_mean_P_1",
                          "Weighted_observed_percentages_mean_S_1", "Weighted_observed_percentages_mean_T_1",
                          "Weighted_observed_percentages_mean_W_1", "Weighted_observed_percentages_mean_Y_1",
                          "Weighted_observed_percentages_mean_V_1", "Mean_information_per_position_mean_1",
                          "Rel_wt_gapless_pseudocount_mean_1", "Substitution_score_mean_A_5", "Substitution_score_mean_R_5",
                          "Substitution_score_mean_N_5", "Substitution_score_mean_D_5", "Substitution_score_mean_C_5",
                          "Substitution_score_mean_Q_5", "Substitution_score_mean_E_5", "Substitution_score_mean_G_5",
                          "Substitution_score_mean_H_5", "Substitution_score_mean_I_5", "Substitution_score_mean_L_5",
                          "Substitution_score_mean_K_5", "Substitution_score_mean_M_5", "Substitution_score_mean_F_5",
                          "Substitution_score_mean_P_5", "Substitution_score_mean_S_5", "Substitution_score_mean_T_5",
                          "Substitution_score_mean_W_5", "Substitution_score_mean_Y_5", "Substitution_score_mean_V_5",
                          "Weighted_observed_percentages_mean_A_5", "Weighted_observed_percentages_mean_R_5",
                          "Weighted_observed_percentages_mean_N_5", "Weighted_observed_percentages_mean_D_5",
                          "Weighted_observed_percentages_mean_C_5", "Weighted_observed_percentages_mean_Q_5",
                          "Weighted_observed_percentages_mean_E_5", "Weighted_observed_percentages_mean_G_5",
                          "Weighted_observed_percentages_mean_H_5", "Weighted_observed_percentages_mean_I_5",
                          "Weighted_observed_percentages_mean_L_5", "Weighted_observed_percentages_mean_K_5",
                          "Weighted_observed_percentages_mean_M_5", "Weighted_observed_percentages_mean_F_5",
                          "Weighted_observed_percentages_mean_P_5", "Weighted_observed_percentages_mean_S_5",
                          "Weighted_observed_percentages_mean_T_5", "Weighted_observed_percentages_mean_W_5",
                          "Weighted_observed_percentages_mean_Y_5", "Weighted_observed_percentages_mean_V_5",
                          "Mean_information_per_position_mean_5", "Rel_wt_gapless_pseudocount_mean_5",
                          "Substitution_score_mean_A_11", "Substitution_score_mean_R_11", "Substitution_score_mean_N_11",
                          "Substitution_score_mean_D_11", "Substitution_score_mean_C_11", "Substitution_score_mean_Q_11", "Substitution_score_mean_E_11", "Substitution_score_mean_G_11", "Substitution_score_mean_H_11",
                          "Substitution_score_mean_I_11", "Substitution_score_mean_L_11", "Substitution_score_mean_K_11", "Substitution_score_mean_M_11", "Substitution_score_mean_F_11", "Substitution_score_mean_P_11",
                          "Substitution_score_mean_S_11", "Substitution_score_mean_T_11", "Substitution_score_mean_W_11", "Substitution_score_mean_Y_11", "Substitution_score_mean_V_11", "Weighted_observed_percentages_mean_A_11",
                          "Weighted_observed_percentages_mean_R_11", "Weighted_observed_percentages_mean_N_11", "Weighted_observed_percentages_mean_D_11", "Weighted_observed_percentages_mean_C_11", "Weighted_observed_percentages_mean_Q_11",
                          "Weighted_observed_percentages_mean_E_11", "Weighted_observed_percentages_mean_G_11", "Weighted_observed_percentages_mean_H_11", "Weighted_observed_percentages_mean_I_11", "Weighted_observed_percentages_mean_L_11",
                          "Weighted_observed_percentages_mean_K_11", "Weighted_observed_percentages_mean_M_11", "Weighted_observed_percentages_mean_F_11", "Weighted_observed_percentages_mean_P_11", "Weighted_observed_percentages_mean_S_11",
                          "Weighted_observed_percentages_mean_T_11", "Weighted_observed_percentages_mean_W_11", "Weighted_observed_percentages_mean_Y_11", "Weighted_observed_percentages_mean_V_11", "Mean_information_per_position_mean_11",
                          "Rel_wt_gapless_pseudocount_mean_11", "Substitution_score_mean_A_21", "Substitution_score_mean_R_21", "Substitution_score_mean_N_21", "Substitution_score_mean_D_21", "Substitution_score_mean_C_21", "Substitution_score_mean_Q_21",
                          "Substitution_score_mean_E_21", "Substitution_score_mean_G_21", "Substitution_score_mean_H_21", "Substitution_score_mean_I_21", "Substitution_score_mean_L_21", "Substitution_score_mean_K_21", "Substitution_score_mean_M_21",
                          "Substitution_score_mean_F_21", "Substitution_score_mean_P_21", "Substitution_score_mean_S_21", "Substitution_score_mean_T_21", "Substitution_score_mean_W_21", "Substitution_score_mean_Y_21", "Substitution_score_mean_V_21",
                          "Weighted_observed_percentages_mean_A_21", "Weighted_observed_percentages_mean_R_21", "Weighted_observed_percentages_mean_N_21", "Weighted_observed_percentages_mean_D_21", "Weighted_observed_percentages_mean_C_21",
                          "Weighted_observed_percentages_mean_Q_21", "Weighted_observed_percentages_mean_E_21", "Weighted_observed_percentages_mean_G_21", "Weighted_observed_percentages_mean_H_21", "Weighted_observed_percentages_mean_I_21",
                          "Weighted_observed_percentages_mean_L_21", "Weighted_observed_percentages_mean_K_21", "Weighted_observed_percentages_mean_M_21", "Weighted_observed_percentages_mean_F_21", "Weighted_observed_percentages_mean_P_21",
                          "Weighted_observed_percentages_mean_S_21", "Weighted_observed_percentages_mean_T_21", "Weighted_observed_percentages_mean_W_21", "Weighted_observed_percentages_mean_Y_21", "Weighted_observed_percentages_mean_V_21",
                          "Mean_information_per_position_mean_21", "Rel_wt_gapless_pseudocount_mean_21", "PSSM_exist"]